app: insta-ritter
service: insta-ritter
tenant: hyanmandian
stage: dev
region: us-east-1

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  all:
    handler: src/handler/all.handler
    events:
      - http:
          path: photos
          method: get
          cors: true
  find:
    handler: src/handler/find.handler
    events:
      - http:
          path: photos/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  root: 
    handler: src/handler/index.handler           
    events:
      - http:
          path: /
          method: get
          cors: true   
