app: insta-ritter
service: insta-ritter
tenant: hyanmandian
stage: dev
region: us-east-1

plugins:
  - serverless-offline
  - serverless-s3-local

provider:
  name: aws
  runtime: nodejs8.10

custom:
 s3:
    host: 0.0.0.0
    port: 7000
    directory: /tmp

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket  

functions:
  all:
    handler: src/handlers/all.handler
    events:
      - http:
          path: photos
          method: get
          cors: true
  store:
    handler: src/handlers/store.handler
    events:
      - http:
          path: photos
          method: post
          cors: true
  find:
    handler: src/handlers/find.handler
    events:
      - http:
          path: photos/{id}
          method: get
          cors: true
  destroy:
    handler: src/handlers/destroy.handler
    events:
      - http:
          path: photos/{id}
          method: delete
          cors: true
